In [1]:
!pip install kaggle

In [2]:
from google.colab import files
upload = files.upload()

Saving kaggle.json to kaggle.json


In [0]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle competitions download -c buildnet

  0% 0.00/495k [00:00<?, ?B/s]
100% 495k/495k [00:00<00:00, 66.8MB/s]
 81% 5.00M/6.17M [00:00<00:00, 6.66MB/s]
100% 6.17M/6.17M [00:00<00:00, 7.93MB/s]
 64% 5.00M/7.86M [00:00<00:00, 8.70MB/s]
100% 7.86M/7.86M [00:00<00:00, 12.4MB/s]
  0% 0.00/2.66M [00:00<?, ?B/s]
100% 2.66M/2.66M [00:00<00:00, 87.4MB/s]
 60% 5.00M/8.33M [00:00<00:00, 6.93MB/s]
100% 8.33M/8.33M [00:00<00:00, 10.7MB/s]
 77% 25.0M/32.7M [00:01<00:00, 13.5MB/s]
100% 32.7M/32.7M [00:01<00:00, 26.0MB/s]
 53% 17.0M/32.3M [00:00<00:01, 13.6MB/s]
100% 32.3M/32.3M [00:00<00:00, 47.3MB/s]
100% 41.8M/41.8M [00:01<00:00, 22.3MB/s]

  0% 0.00/1.21k [00:00<?, ?B/s]
100% 1.21k/1.21k [00:00<00:00, 1.02MB/s]
  0% 0.00/140 [00:00<?, ?B/s]
100% 140/140 [00:00<00:00, 112kB/s]
  0% 0.00/288 [00:00<?, ?B/s]
100% 288/288 [00:00<00:00, 348kB/s]
  0% 0.00/336 [00:00<?, ?B/s]
100% 336/336 [00:00<00:00, 337kB/s]
  0% 0.00/200 [00:00<?, ?B/s]
100% 200/200 [00:00<00:00, 230kB/s]
  0% 0.00/348 [00:00<?, ?B/s]
100% 348/348 [00:00<00:00, 286kB/s]
  

In [5]:
!ls
!unzip 
!unzip 
!unzip Grad3.npy.zip
!unzip Grad4.npy.zip
!unzip Grad5.npy.zip


kaggle.json			   Train_with_no_collapse.npy.zip
sample_data			   yTest_with_full_collapse.npy
Test_with_full_collapse.npy.zip    yTest_with_major_collapse.npy
Test_with_major_collapse.npy.zip   yTest_with_minor_collapse.npy
Test_with_minor_collapse.npy.zip   yTest_with_no_collapse.npy
Test_with_no_collapse.npy.zip	   yTrain_with_full_collapse.npy
Train_with_full_collapse.npy.zip   yTrain_with_major_collapse.npy
Train_with_major_collapse.npy.zip  yTrain_with_minor_collapse.npy
Train_with_minor_collapse.npy.zip  y_train_with_no_collapse.npy
unzip:  cannot find or open Grad1.npy.zip, Grad1.npy.zip.zip or Grad1.npy.zip.ZIP.
unzip:  cannot find or open Grad2.npy.zip, Grad2.npy.zip.zip or Grad2.npy.zip.ZIP.
unzip:  cannot find or open Grad3.npy.zip, Grad3.npy.zip.zip or Grad3.npy.zip.ZIP.


KeyboardInterrupt: ignored

In [0]:
import numpy as np
y_train1 = np.load('y_train_1.npy')
y_train2 = np.load('y_train_2.npy')
y_train3 = np.load('y_train_3.npy')
y_train4 = np.load('y_train_4.npy')
y_train5 = np.load('y_train_5.npy')
y_traina = np.concatenate((y_train1, y_train2, y_train3, y_train4, y_train5), axis = 0)
print(y_train1.shape)
print(y_train2.shape)
print(y_train3.shape)
print(y_train4.shape)
print(y_train5.shape)
print(y_traina.shape)
for i in range (len(y_train2)):
  y_train2[i] = 1

print(y_train2, len(y_train2))

for i in range(len(y_train3)):
  y_train3[i] = 2
  
print(y_train3, len(y_train3))

for i in range(len(y_train4)):
  y_train4[i] = 3

print(y_train4, len(y_train4))
  
for i in range(len(y_train5)):
  y_train5[i] = 4
  
print(y_train5, len(y_train5))
print(y_train1, len(y_train1))

(175,)
(133,)
(165,)
(59,)
(51,)
(583,)
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 133
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] 165
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3] 59
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4] 51
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [0]:
X_train1 = np.load('Grad1.npy')
X_train2 = np.load('Grad2.npy')
X_train3 = np.load('Grad3.npy')
X_train4 = np.load('Grad4.npy')
X_train5 = np.load('Grad5.npy')
X_train1 = np.concatenate((X_train1, X_train2), axis = 0)
X_traina = np.concatenate((X_train1, X_train3, X_train4, X_train5), axis = 0)
X_train1_train = X_train1[:265]
X_train1_val = X_train1[265:]
X_train3_train = X_train3[:145]
X_train3_val = X_train3[145:]
X_train4_train = X_train4[:54]
X_train4_val = X_train4[54:]
X_train5_train = X_train5[:47]
X_train5_val = X_train5[47:]

print(X_train1.shape)

print(X_train3.shape)
print(X_train4.shape)
print(X_train5.shape)
print(X_traina.shape)

(308, 224, 224, 3)
(165, 224, 224, 3)
(59, 224, 224, 3)
(51, 224, 224, 3)
(583, 224, 224, 3)


In [0]:
def y_out(y, num_classes = 4):
  y1 = np.zeros((y.shape[0],num_classes))
  for i in range(len(y)):
    y1[i,y[i]-1] = 1
  
  return y1
y_train1 = np.concatenate((y_train1, y_train2), axis = 0)
y_train1 = y_out(y_train1)
y_train3 = y_out(y_train3)
y_train4 = y_out(y_train4)
y_train5 = y_out(y_train5)
X_train = np.concatenate((X_train1_train, X_train3_train, X_train4_train, X_train5_train), axis = 0)
X_val = np.concatenate((X_train1_val, X_train3_val, X_train4_val, X_train5_val), axis = 0)
y_train1_train = y_train1[:265]
y_train1_val = y_train1[265:]
y_train3_train = y_train3[:145]
y_train3_val = y_train3[145:]
y_train4_train = y_train4[:54]
y_train4_val = y_train4[54:]
y_train5_train = y_train5[:47]
y_train5_val = y_train5[47:]
y_train = np.concatenate((y_train1_train, y_train3_train, y_train4_train, y_train5_train), axis = 0)
y_val = np.concatenate((y_train1_val, y_train3_val, y_train4_val, y_train5_val), axis = 0)
print(X_train.shape)
print(y_train.shape)
print(X_val.shape)
print(y_val.shape)

(511, 224, 224, 3)
(511, 4)
(72, 224, 224, 3)
(72, 4)


In [0]:
for i in range(100, 200):
  print(y_train[i])

[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0.

In [0]:
import keras
import numpy as np
import matplotlib.pyplot as plt
from keras import layers
from keras import optimizers
from keras.layers import Dense, Flatten, Activation, Dropout
from keras import applications
from keras.applications import VGG16, InceptionV3, ResNet50

image_size = 224

vgg_conv = ResNet50(weights = 'imagenet', include_top = False, input_shape=(image_size, image_size, 3))

vgg_conv.summary()

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.


/usr/local/lib/python3.6/dist-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 112, 112, 64) 256         conv1[0][0]                      
__________________________________________________________________________________________________
activation

In [0]:
from google.colab import files

upload = files.upload()

Saving resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5 to resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5


In [0]:
weights_path = 'resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5'

In [0]:
from keras.models import Sequential, Model, load_model

vgg_conv.load_weights(weights_path)

x = Flatten()(vgg_conv.get_layer('activation_49').output)
x = Dense(512, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(4, activation='softmax')(x)

model = Model(inputs = vgg_conv.input, outputs = x)
model.compile(loss='categorical_crossentropy', optimizer = optimizers.Adam(lr=0.00004, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False), metrics = ['accuracy'])

model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 112, 112, 64) 256         conv1[0][0]                      
__________________________________________________________________________________________________
activation

In [0]:
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint

batch_size = 20
epochs = 160

train_datagen = ImageDataGenerator(rotation_range = 10, width_shift_range = 0.1, height_shift_range = 0.1, horizontal_flip=True)

history = model.fit_generator(train_datagen.flow(X_train, y_train, batch_size = batch_size),
                             steps_per_epoch = X_train.shape[0] // batch_size,
                             epochs = epochs,
                             validation_data = (X_val, y_val),
                             callbacks=[ModelCheckpoint('ResNet50-transferlearning.model', monitor='val_acc', save_best_only=True)])

Epoch 1/160
25/25 [==============================] - 34s 1s/step - loss: 2.5554 - acc: 0.4520 - val_loss: 1.0103 - val_acc: 0.5278
Epoch 2/160
25/25 [==============================] - 18s 738ms/step - loss: 1.5942 - acc: 0.5478 - val_loss: 0.9506 - val_acc: 0.5694
Epoch 3/160
25/25 [==============================] - 18s 727ms/step - loss: 1.2500 - acc: 0.6199 - val_loss: 1.0039 - val_acc: 0.6389
Epoch 4/160
25/25 [==============================] - 18s 734ms/step - loss: 1.0357 - acc: 0.6751 - val_loss: 0.9332 - val_acc: 0.5972
Epoch 5/160
25/25 [==============================] - 18s 730ms/step - loss: 0.7111 - acc: 0.7435 - val_loss: 0.8834 - val_acc: 0.6389
Epoch 6/160
25/25 [==============================] - 18s 729ms/step - loss: 0.6187 - acc: 0.7827 - val_loss: 0.8270 - val_acc: 0.7083
Epoch 7/160
25/25 [==============================] - 18s 736ms/step - loss: 0.4861 - acc: 0.8051 - val_loss: 0.9283 - val_acc: 0.6389
Epoch 8/160
25/25 [==============================] - 18s 729ms/st